### ISSUE TITLE
Question: Will this be safe to use with Heroku?

### ISSUE THREAD

**Issue by nitronapp** [AHgPuK/strapi-mongodb-files#1]
First thanks for your kind efforts in creating the upload provider. I would like to know if this will be fine to use when deploying with [Heroku](https://www.heroku.com/)?

As you may have known that the file system in [Heroku](https://www.heroku.com/) doesn't support local uploading of files as they will be wiped when Heroku "Cycles" the dyno.

**Comment by AHgPuK** [comment]
Sure. Works fine. It is not an environment dependent. It will use MongoDB instance you work with.
This provider-plugin won't work yet on Strapi environments which use other DB except MongoDB.
I suppose to make it configurable in the future.
@MahmudHamid
