### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by rahulbhooteshwar** [AHgPuK/strapi-mongodb-files#2]
Current Documentation doesn't provide the details about specifying MongoDB credentials while configuring the provider.

Please specify the key name to be used for MongDB related stuff.

**Comment by AHgPuK** [comment]
As you can see at the most first sentence it is intended for using with Strapi+MongoDB.
It will use the same MongoDB connection that Strapi has, so you don't need to configure any credentials.
If you suppose to support alternative MongoDB instance you can open feature request for that.

**Comment by rahulbhooteshwar** [comment]
> As you can see at the most first sentence it is intended for using with Strapi+MongoDB.
My Bad. Thanks. Now I get it.
