### ISSUE TITLE
Fetch the uploaded Image URL not found

### ISSUE THREAD

**Issue by Natrajz** [AHgPuK/strapi-mongodb-files#4]
Hi @AHgPuK , I tried this package to upload the files in Mongodb. once after installation, i can see the uploaded image in MongoDB folders like fs.chunks, fs.files, upload_file. but i can't use the image in client side when i tried to load it in browser http://localhost:1337/files/1594393370742.jpeg. 

I followed your instruction to created the setting.json file under the upload extensions.  How can i fetch the images in strapi?
This is the sample data image, but when access the URL, it shows the **not found**

![image](https://user-images.githubusercontent.com/24310952/87520861-2d48c700-c6a1-11ea-93f4-f583c9e5144a.png)

**Comment by AHgPuK** [comment]
Hi,
Try to open http://localhost:1337/files/1594393370742 without ".jpeg"
It is a known issue in strapi 3.0.0
Fix will be released in 3.0.6

**Comment by Natrajz** [comment]
Thanks for your quick reply @AHgPuK :)
yeah, i tired it also but when i access the url it will automatically download one file. i can't see it in browser. my current Strapi  version is 3.0.5. can you please help to sort out the issue.

**Comment by AHgPuK** [comment]
You need to wait for 3.0.6

**Comment by AHgPuK** [comment]
3.0.6 is released
